CREATE TABLE IF NOT EXISTS "QuoteRecommendation" (
  "QuoteRecommendationID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT NOT NULL REFERENCES "Customer" ("CustomerID"),
  "HealthProfileID" INT NOT NULL REFERENCES "CustomerHealthProfile" ("HealthProfileID"),
  "RiskTier" varchar(20) NOT NULL,
  "BaseMonthlyRate" decimal(12,2) NOT NULL,
  "RateAdjustmentFactor" decimal(5,2) NOT NULL,
  "RecommendedMonthlyRate" decimal(12,2) NOT NULL,
  "RecommendationReason" varchar(255),
  "CreatedDate" date NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_quoterecommendation_customer
ON "QuoteRecommendation" ("CustomerID");

CREATE INDEX IF NOT EXISTS idx_quoterecommendation_healthprofile
ON "QuoteRecommendation" ("HealthProfileID");

COMMENT ON TABLE "QuoteRecommendation" IS
'Stores lifestyle risk tier and insurance rate recommendation from the Part 4 Centers for Disease Control and Prevention BRFSS and Centers for Medicare & Medicaid Services Rate PUF workflow.';
