CREATE TABLE "Account" (
  "AccountID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CompanyCode" varchar(20) NOT NULL,
  "AccountName" varchar(150) NOT NULL,
  "Address1" varchar(150),
  "City" varchar(80),
  "State" varchar(30),
  "Zip" varchar(15),
  "Status" varchar(30)
);

CREATE TABLE "BillingAccount" (
  "BillingAccountID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "POBox" varchar(50),
  "BillingAddress" varchar(150),
  "InvoiceType" varchar(50),
  "Status" varchar(30)
);

CREATE TABLE "AccountAdmin" (
  "AccountAdminID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AdminName" varchar(120) NOT NULL,
  "Specialty" varchar(80),
  "Phone" varchar(30),
  "Email" varchar(120)
);

CREATE TABLE "AccountAlias" (
  "AccountAliasID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AccountID" int NOT NULL,
  "SourceSystem" varchar(50),
  "OriginalAccountName" varchar(150),
  "OriginalAddress" varchar(150),
  "OriginalCity" varchar(80),
  "OriginalState" varchar(30),
  "OriginalZip" varchar(15),
  "ReviewStatus" varchar(30),
  "LoadDate" date
);

CREATE TABLE "Associate" (
  "AssociateID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(80),
  "LastName" varchar(80),
  "LicenseState" varchar(30),
  "Status" varchar(30)
);

CREATE TABLE "ManagerContract" (
  "ManagerContractID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssociateID" int NOT NULL,
  "WritingNumber" varchar(40),
  "SitCode" varchar(40),
  "StateCode" varchar(30),
  "EffectiveDate" date,
  "EndDate" date,
  "IsOfficialChain" boolean
);

CREATE TABLE "Contract" (
  "ContractID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ContractNumber" varchar(50) UNIQUE NOT NULL,
  "ContractType" varchar(50),
  "EffectiveDate" date,
  "EndDate" date,
  "Status" varchar(30)
);

CREATE TABLE "ContractBenefit" (
  "ContractBenefitID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ContractID" int NOT NULL,
  "BenefitType" varchar(60),
  "CoveredPersonType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date
);

CREATE TABLE "ContractPremium" (
  "ContractPremiumID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ContractBenefitID" int NOT NULL,
  "PremiumAmount" decimal(12,2),
  "AccountingType" varchar(40),
  "PremiumPeriod" varchar(30),
  "EffectiveDate" date,
  "EndDate" date
);

CREATE TABLE "Customer" (
  "CustomerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerType" varchar(30) NOT NULL,
  "FirstName" varchar(80),
  "LastName" varchar(80),
  "OrganizationName" varchar(150),
  "DOB" date,
  "Status" varchar(30)
);

CREATE TABLE "AccountBillingAccount" (
  "AccountID" int,
  "BillingAccountID" int,
  "EmployeeClass" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("AccountID", "BillingAccountID", "EffectiveDate")
);

CREATE TABLE "AccountRelationship" (
  "ParentAccountID" int,
  "ChildAccountID" int,
  "RelationshipType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("ParentAccountID", "ChildAccountID", "RelationshipType", "EffectiveDate")
);

CREATE TABLE "AccountAccountAdmin" (
  "AccountID" int,
  "AccountAdminID" int,
  "AdminRole" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("AccountID", "AccountAdminID", "EffectiveDate")
);

CREATE TABLE "AccountManagerContractRole" (
  "AccountID" int,
  "ManagerContractID" int,
  "RoleType" varchar(50),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("AccountID", "ManagerContractID", "RoleType", "EffectiveDate")
);

CREATE TABLE "ManagerContractUpline" (
  "ManagerContractID" int,
  "UplineManagerContractID" int,
  "UplineLevel" varchar(30),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("ManagerContractID", "UplineManagerContractID", "UplineLevel", "EffectiveDate")
);

CREATE TABLE "AssociateRelationship" (
  "AssociateID1" int,
  "AssociateID2" int,
  "RelationshipType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("AssociateID1", "AssociateID2", "RelationshipType", "EffectiveDate")
);

CREATE TABLE "CustomerRelationship" (
  "CustomerID1" int,
  "CustomerID2" int,
  "RelationshipType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("CustomerID1", "CustomerID2", "RelationshipType", "EffectiveDate")
);

CREATE TABLE "CustomerContractRole" (
  "CustomerID" int,
  "ContractID" int,
  "RoleType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("CustomerID", "ContractID", "RoleType", "EffectiveDate")
);

CREATE TABLE "CustomerContractBenefitRole" (
  "CustomerID" int,
  "ContractBenefitID" int,
  "RoleType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("CustomerID", "ContractBenefitID", "RoleType", "EffectiveDate")
);

CREATE TABLE "CustomerAccountRole" (
  "CustomerID" int,
  "AccountID" int,
  "RoleType" varchar(40),
  "EmploymentStatus" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("CustomerID", "AccountID", "RoleType", "EffectiveDate")
);

CREATE TABLE "CustomerAssociateRole" (
  "CustomerID" int,
  "AssociateID" int,
  "RoleType" varchar(40),
  "EffectiveDate" date,
  "EndDate" date,
  PRIMARY KEY ("CustomerID", "AssociateID", "RoleType", "EffectiveDate")
);

CREATE TABLE "ChronicDisease" (
  "DiseaseID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DiseaseName" varchar(100) UNIQUE NOT NULL,
  "DiseaseCategory" varchar(50),
  "Description" varchar(255)
);

CREATE TABLE "RiskFactor" (
  "RiskFactorID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FactorName" varchar(100) UNIQUE NOT NULL,
  "FactorCategory" varchar(50),
  "IsChangeable" boolean,
  "Description" varchar(255)
);

CREATE TABLE "CustomerHealthProfile" (
  "HealthProfileID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" int NOT NULL,
  "DiseaseID" int NOT NULL,
  "ChronicDiseaseRiskScore" decimal(5,2),
  "PrimaryRiskFactorID" int,
  "AssessmentDate" date,
  "AssessmentMethod" varchar(100),
  "Notes" varchar(255)
);

CREATE TABLE "HealthDataLakeRef" (
  "DataLakeRefID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "HealthProfileID" int NOT NULL,
  "SourceSystem" varchar(100),
  "DataFormat" varchar(20),
  "CloudStorageURI" varchar(500) NOT NULL,
  "DatasetName" varchar(150),
  "LoadDate" date,
  "FileDescription" varchar(255)
);

CREATE UNIQUE INDEX ON "Account" ("CompanyCode", "AccountName", "Address1", "City", "State", "Zip");

COMMENT ON TABLE "Account" IS 'CompanyCode is part of the logical business key.';

COMMENT ON TABLE "AccountAlias" IS 'Stores original unconsolidated source records for cleansing/manual review.';

COMMENT ON TABLE "ChronicDisease" IS 'Stores chronic disease targets such as cardiovascular disease, diabetes, tumor, obesity, and chronic respiratory disease.';

COMMENT ON TABLE "RiskFactor" IS 'Stores disease risk factors from the project diagrams such as smoking/drinking, exercise, heredity, and living standard.';

COMMENT ON TABLE "CustomerHealthProfile" IS 'Stores structured health-risk insights for a customer derived from hybrid data sources.';

COMMENT ON TABLE "HealthDataLakeRef" IS 'Connects structured health profiles to raw cloud-stored files such as JSON and CSV.';

ALTER TABLE "AccountAlias" ADD FOREIGN KEY ("AccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ManagerContract" ADD FOREIGN KEY ("AssociateID") REFERENCES "Associate" ("AssociateID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ContractBenefit" ADD FOREIGN KEY ("ContractID") REFERENCES "Contract" ("ContractID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ContractPremium" ADD FOREIGN KEY ("ContractBenefitID") REFERENCES "ContractBenefit" ("ContractBenefitID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountBillingAccount" ADD FOREIGN KEY ("AccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountBillingAccount" ADD FOREIGN KEY ("BillingAccountID") REFERENCES "BillingAccount" ("BillingAccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountRelationship" ADD FOREIGN KEY ("ParentAccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountRelationship" ADD FOREIGN KEY ("ChildAccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountAccountAdmin" ADD FOREIGN KEY ("AccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountAccountAdmin" ADD FOREIGN KEY ("AccountAdminID") REFERENCES "AccountAdmin" ("AccountAdminID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountManagerContractRole" ADD FOREIGN KEY ("AccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AccountManagerContractRole" ADD FOREIGN KEY ("ManagerContractID") REFERENCES "ManagerContract" ("ManagerContractID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ManagerContractUpline" ADD FOREIGN KEY ("ManagerContractID") REFERENCES "ManagerContract" ("ManagerContractID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ManagerContractUpline" ADD FOREIGN KEY ("UplineManagerContractID") REFERENCES "ManagerContract" ("ManagerContractID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AssociateRelationship" ADD FOREIGN KEY ("AssociateID1") REFERENCES "Associate" ("AssociateID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AssociateRelationship" ADD FOREIGN KEY ("AssociateID2") REFERENCES "Associate" ("AssociateID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerRelationship" ADD FOREIGN KEY ("CustomerID1") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerRelationship" ADD FOREIGN KEY ("CustomerID2") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerContractRole" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerContractRole" ADD FOREIGN KEY ("ContractID") REFERENCES "Contract" ("ContractID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerContractBenefitRole" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerContractBenefitRole" ADD FOREIGN KEY ("ContractBenefitID") REFERENCES "ContractBenefit" ("ContractBenefitID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerAccountRole" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerAccountRole" ADD FOREIGN KEY ("AccountID") REFERENCES "Account" ("AccountID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerAssociateRole" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerAssociateRole" ADD FOREIGN KEY ("AssociateID") REFERENCES "Associate" ("AssociateID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerHealthProfile" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerHealthProfile" ADD FOREIGN KEY ("DiseaseID") REFERENCES "ChronicDisease" ("DiseaseID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CustomerHealthProfile" ADD FOREIGN KEY ("PrimaryRiskFactorID") REFERENCES "RiskFactor" ("RiskFactorID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "HealthDataLakeRef" ADD FOREIGN KEY ("HealthProfileID") REFERENCES "CustomerHealthProfile" ("HealthProfileID") DEFERRABLE INITIALLY IMMEDIATE;

